### ISSUE TITLE
Slides template for presentations

### ISSUE THREAD

**Issue by kateswade** [DigitalCommons/allthethings#1]
## Description
We need a flexible branded slide deck template
it should:
- have the DC logo, colours and branding
- have a consistent approach to fonts
- have a variety of types of slides, like some with a title and bullet points, some just for an image, one with a big font for highlighting a figure or key words
- have an option for inserting a video
- make us look cool 😎
- be 100% usable on google suite as Kate doesn't have any microsoft tools on her computer so can't edit or work with powerpoint  files other than in google docs

## How will I know this is completed?
- we have a usable slide deck template!
- we have agreed the best way to work with the template - eg does it need to be copypasted into a new file, is it saved as a template in the google suite so we can just choose it when starting a new file etc

**Comment by kateswade** [comment]
I can't seem to assign this to anyone - I've signed into zen hub but it wants me to create a pipeline in order to assign things to people and I don't have the necessary push / write permissions apparently :)

**Comment by MelissaMc20** [comment]
@kateswade all feedback welcome :) 

https://docs.google.com/presentation/d/1Bh8GytRxbul798bno5S4atL5LicoIas6/edit#slide=id.p1

**Comment by kateswade** [comment]
hi @MelissaMc20 sorry for the delay! I like the general vibe a lot. A couple of comments:
- would it be possible to make it a standard 16:9 size? it's currently a custom size which I can see might be problematic when sharing or if we ever need to integrate our slides with others...
- would it be possible to make this into a template file within google slides itself so the options come up when you click "layout"  (and so you can't accidentally move the images around!) - ah I've just checked and it's not possible on the free version of google workspace, so scrap that! we will need to be v careful about keeping a clean version and copy and pasting it :)
- it would be good to have text boxes already there with the right font on slides 2 and 3
- thanks!

**Comment by kateswade** [comment]
also a small nudge on this @MelissaMc20 :)

**Comment by MelissaMc20** [comment]
@kateswade - this is all done. They're marked as 16:9 and I've added text boxes to those slides

**Comment by kateswade** [comment]
hi @MelissaMc20 - sorry to be just picking this up now, I don't think I am getting notificaitons from github when someone tags me! Thanks for this. I will delete the wrong sized ones so we don't get confused :)
